name: aib_test
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dartz: 0.10.1
  dio: 5.3.0

  flutter_bloc: 8.1.3
  go_router: 10.0.0
  get_it: 7.6.0
  freezed_annotation: 2.4.1
  build_runner: 2.4.6
  json_serializable: 6.7.1
  freezed: 2.4.1
  json_annotation: 4.8.1

  package_info_plus: 4.1.0

dev_dependencies:

  bloc_test: 9.1.3
  mockito: 5.4.2
  
  flutter_lints: 2.0.2
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

